name: Docker Installation

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Ubuntu
        run: |
          sudo apt update

      - name: Install Docker
        run: |
          sudo apt install -y docker.io

      - name: Check Docker Version
        run: |
          docker --version

      - name: Start Docker Service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Test Docker
        run: |
          sudo docker run hello-world
