name: Docker Install

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Old Docker Packages
        run: |
          sudo apt-get remove -y containerd containerd.io docker.io docker-ce docker-ce-cli || true

      - name: Update Packages
        run: |
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io

      - name: Start Docker
        run: |
          sudo systemctl start docker

      - name: Docker Version
        run: |
          docker --version

      - name: Test Docker
        run: |
          docker run hello-world
